---
- name: Safe system update on Debian
  hosts: adguard
  become: true

  tasks:

    - name: Update APT index
      apt:
        update_cache: yes
        upgrade: full
        autoremove: yes
        autoclean: yes
      register: apt
    - name: powiadomienia
      community.general.slack:
        token: T09T0AVUCV9/B09U132N3GQ/AQorXCga2iH2lV6Y9OUtDhvN
        username: 'Debian'
        msg: "Status aktualizacji: {{ apt.stdout_lines }}"
        
